POST http://localhost:9090/authentication/signup
Content-Type: application/json

{
    "FirstName":"ahmed",
    "LastName":"mohamed",
    "Email":"ahmed1@gmail.com",
    "Password" : "#Aa334455",
    "Phone":"197112240",
    "DOB":"2025-5-12"

}

###
POST http://localhost:9090/authentication/login
Content-Type: application/json

{
    "Email":"ahmed1@gmail.com",
    "Password" : "#Aa334455"
}